<a href="https://colab.research.google.com/github/Estebansalazar/pytorchprojects/blob/master/Linnear_regresion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch

In [0]:
import torch
from torch.nn import Linear

In [7]:
#el seed nos da los mismos randoms que el tutorial
torch.manual_seed(1)
#creamos un objeto que nos indica que para cada input tendremos un output
model = Linear(in_features=1,out_features=1)
print(model.bias,model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [9]:
#creamos un tensor de entrada y se lo agregamos al modelo
x = torch.tensor([[2.0],[3.3]])
#le agregamos el tensor de entrada a nuestro modelo
model(x)


tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward>)