In [1]:
!pip3 install torch

In [0]:
import torch

In [8]:
#transformamos este vector en una matriz de 2x3 (view(2,3))
mat_a=torch.tensor([8,7,5,4,2,2]).view(2,3)
mat_a

tensor([[8, 7, 5],
        [4, 2, 2]])

In [10]:
#transformamos este vector en una matriz de 3x2 (view(3,2))

mat_b=torch.tensor([3,4,3,-2,4,-2]).view(3,2)
mat_b

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [11]:
#multiplicame la matriz a con la b
torch.matmul(mat_a,mat_b)

tensor([[65,  8],
        [26,  8]])